version: "3.1"
services:
  app:
    image: tghuy2002/smarty_blogs
    ports:
      - 3000:3000
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: smarty-blogs
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - app-network
    environment:
      PMA_HOST: db

networks:
  app-network:
    driver: bridge
