name: Deploy to Azure VPS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Azure VPS
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh tghuy@40.82.152.192 'cd /home/tghuy/smarty-blogs && git pull origin main && docker-compose up -d'
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
